package com.java.general;

public class BridgeMethod {
	
	public static void main(String args[]){
		
	}
}

 class Node<T> {
	public T data;
	
    public Node(T data) { 
    	this.data = data; 
    }

    public void setData(T data) {
        this.data = data;
    }
    
    /* Method Signature after type Erasure.
     public void setData(Object data) {
        this.data = data;
    }
     * */

}

 class MyNode extends Node<Integer> {
    public MyNode(Integer data) { 
    	super(data); 
    }
    
    // After the type erasure compiler will add a new bridge method as setData in Node and MyNode will be different.
    public void setData(Integer data) {
        super.setData(data);
    }
    
    // Bridge method generated by the compiler.
    //
    /*public void setData(Object data) {
        setData((Integer) data);
    }*/

}
